### ISSUE TITLE
BUG: user controller is not compatible with the old version of the user resource

### ISSUE THREAD

**Issue by bxy4543** [cuisongliu/sealos#581]
### Sealos Version

user

### How to reproduce the bug?

The new version of user controller is not compatible with the old version of user：
![image](https://github.com/cuisongliu/sealos/assets/69408038/566cf2e3-aaaf-4dfd-b437-81ac2ae288cc)

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

**Comment by cuisongliu** [comment]
done
